name: gfive
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  firebase_core: "0.5.0"
  firebase_auth: ^0.18.0
  cloud_firestore: ^0.14.0
  flutter_spinkit: ^4.1.2+1
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.1
  firebase_storage: ^4.0.0
  fluttertoast: ^7.0.2
  cached_network_image: ^2.2.0+1
  intl: ^0.16.1
  flutter_local_notifications: ^1.4.4+3
  photo_view: ^0.10.1
  shared_preferences: ^0.5.8 
  image_picker: ^0.6.7+4
    
  firebase_messaging: ^7.0.0
   

    
dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  
flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/uni1.png"  


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    # - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700